FROM quay.io/cdis/golang-build-base:master AS go-builder

COPY api/ /app

WORKDIR /app/gen3-agent

RUN go build -o agent

RUN chmod +x agent


FROM quay.io/cdis/golang-build-base:master AS final

COPY --from=go-builder /app/gen3-agent /app/gen3-agent

ENV PATH=/app/gen3-agent:$PATH

WORKDIR /app/gen3-agent 

CMD ["agent"]