
services:
  agent:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.agent
    restart: always
    environment:
      KUBECONFIG: /root/.kube/config
    volumes:
      - ./api/certs:/app/gen3-agent/certs
      - /Users/qureshi/.kube/local.yaml:/root/.kube/config
    command:
      - ./gen3-agent
      - --name
      - kind
  api:
    network_mode: host
    environment:
      KUBECONFIG: /root/.kube/config
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8002:8002"
      - "50051:50051"
    volumes:
      - ./api/certs:/go/src/gen3-admin-api/certs
      - ./api/.env:/go/src/gen3-admin-api/.env
      - /Users/qureshi/.kube/local.yaml:/root/.kube/config
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3002:3000"
    command: 
      - npm
      - run
      - start
    network_mode: host
    # volumes:
      # - ./gen3-admin-frontend:/app/frontend
  