import { useState } from 'react';

import {
  Alert,
  Anchor,
  Badge,
  Button,
  Code,
  Group,
  Modal,
  Stack,
  Table,
  Text,
  Tooltip,
} from '@mantine/core';
import { IconAlertTriangle, IconArrowBackUp } from '@tabler/icons-react';

import { EmptyState } from '@/components/ui';

/**
 * Deployment history with rollback.
 *
 * Commit metadata (author, date, message) is resolved server-side and attached to
 * each entry, so this renders in one request rather than one per revision.
 */

/** Turn a repo URL + revision into a browsable commit link where we recognise the host. */
function commitUrl(repoURL, revision) {
  if (!repoURL || !revision) return null;
  // Chart versions are not commits.
  if (!/^[0-9a-f]{7,40}$/i.test(revision)) return null;

  const normalised = repoURL.replace(/\.git$/, '').replace(/^git@([^:]+):/, 'https://$1/');
  if (/github\.com/.test(normalised)) return `${normalised}/commit/${revision}`;
  if (/gitlab\.com/.test(normalised)) return `${normalised}/-/commit/${revision}`;
  if (/bitbucket\.org/.test(normalised)) return `${normalised}/commits/${revision}`;
  return null;
}

function shortRevision(revision) {
  if (!revision) return '-';
  return /^[0-9a-f]{40}$/i.test(revision) ? revision.slice(0, 7) : revision;
}

/** History entries use `revision` (single source) or `revisions` (multi source). */
function entryRevision(entry) {
  return entry.revision || entry.revisions?.[0] || '';
}

function entryRepo(entry) {
  return entry.source?.repoURL || entry.sources?.[0]?.repoURL || '';
}

function formatDate(value) {
  if (!value) return '-';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '-';
  return date.toLocaleString();
}

export default function HistoryTable({
  items,
  automatedSyncEnabled,
  ownedByApplicationSet,
  currentRevision,
  onRollback,
  rollingBack,
  degraded = false,
}) {
  const [pending, setPending] = useState(null);

  if (!items?.length) {
    return (
      <EmptyState
        title="No deployment history"
        description="ArgoCD records history as an application is synced; nothing has been recorded yet."
      />
    );
  }

  // Rolling back an app with automated sync is pointless: the controller
  // immediately syncs it forward again. Explain rather than silently disable.
  const rollbackBlockedReason = automatedSyncEnabled
    ? 'Automated sync is enabled, so ArgoCD would immediately re-sync forward. Disable automated sync first.'
    : degraded
      ? 'Rollback needs the ArgoCD API, which is currently unreachable.'
      : null;

  return (
    <Stack gap="sm">
      {ownedByApplicationSet && (
        <Alert variant="light" color="statusWarn" icon={<IconAlertTriangle size={18} />} title="Managed by an ApplicationSet">
          This application is generated by an ApplicationSet. A rollback may be reverted the next
          time the generator reconciles.
        </Alert>
      )}

      {automatedSyncEnabled && (
        <Alert variant="light" color="statusInfo" title="Automated sync is enabled">
          ArgoCD syncs this application automatically, so rollback is unavailable.
        </Alert>
      )}

      <Table>
        <Table.Thead>
          <Table.Tr>
            <Table.Th>Revision</Table.Th>
            <Table.Th>Deployed</Table.Th>
            <Table.Th>Author</Table.Th>
            <Table.Th>Message</Table.Th>
            <Table.Th />
          </Table.Tr>
        </Table.Thead>
        <Table.Tbody>
          {items.map((entry) => {
            const revision = entryRevision(entry);
            const link = commitUrl(entryRepo(entry), revision);
            const isCurrent = currentRevision && revision && currentRevision === revision;

            return (
              <Table.Tr key={entry.id}>
                <Table.Td>
                  <Group gap="xs" wrap="nowrap">
                    {link ? (
                      <Anchor href={link} target="_blank" rel="noreferrer" size="sm">
                        <Code>{shortRevision(revision)}</Code>
                      </Anchor>
                    ) : (
                      <Code>{shortRevision(revision)}</Code>
                    )}
                    {isCurrent && <Badge size="xs" color="statusOk">current</Badge>}
                  </Group>
                </Table.Td>
                <Table.Td>
                  <Text size="sm">{formatDate(entry.deployedAt)}</Text>
                </Table.Td>
                <Table.Td>
                  <Text size="sm">{entry.metadata?.author || '-'}</Text>
                </Table.Td>
                <Table.Td>
                  <Text size="sm" lineClamp={2} title={entry.metadata?.message}>
                    {entry.metadata?.message || '-'}
                  </Text>
                </Table.Td>
                <Table.Td>
                  {isCurrent ? null : rollbackBlockedReason ? (
                    <Tooltip label={rollbackBlockedReason} multiline w={260}>
                      <Button size="xs" variant="light" disabled leftSection={<IconArrowBackUp size={14} />}>
                        Rollback
                      </Button>
                    </Tooltip>
                  ) : (
                    <Button
                      size="xs"
                      variant="light"
                      leftSection={<IconArrowBackUp size={14} />}
                      onClick={() => setPending(entry)}
                    >
                      Rollback
                    </Button>
                  )}
                </Table.Td>
              </Table.Tr>
            );
          })}
        </Table.Tbody>
      </Table>

      <Modal
        opened={Boolean(pending)}
        onClose={() => setPending(null)}
        title="Roll back application"
      >
        <Stack gap="md">
          <Text size="sm">
            This deploys revision <Code>{shortRevision(entryRevision(pending || {}))}</Code> again,
            replacing what is currently running.
          </Text>
          {pending?.metadata?.message && (
            <Alert variant="light" color="statusNeutral" title="Commit">
              <Text size="sm">{pending.metadata.message}</Text>
              <Text size="xs" c="dimmed" mt={4}>
                {pending.metadata.author} · {formatDate(pending.metadata.date)}
              </Text>
            </Alert>
          )}
          <Alert variant="light" color="statusWarn" icon={<IconAlertTriangle size={16} />}>
            Git is not changed by a rollback. The next sync from Git will move the application
            forward again unless the revision is also reverted there.
          </Alert>
          <Group justify="flex-end" gap="xs">
            <Button variant="subtle" onClick={() => setPending(null)}>
              Cancel
            </Button>
            <Button
              color="statusWarn"
              loading={rollingBack}
              onClick={() => {
                onRollback?.(pending);
                setPending(null);
              }}
            >
              Roll back
            </Button>
          </Group>
        </Stack>
      </Modal>
    </Stack>
  );
}
