import { useEffect, useMemo, useState } from 'react';

import {
  Alert,
  Badge,
  Button,
  Code,
  Divider,
  Group,
  Modal,
  Paper,
  Stack,
  Text,
  TextInput,
} from '@mantine/core';
import { IconAlertTriangle, IconGitBranch } from '@tabler/icons-react';

import { ErrorState } from '@/components/ui';

/**
 * Edit an application's source: branch, tag, commit or Helm chart version.
 *
 * Multi-source applications are handled explicitly. Conflating `spec.source` with
 * `spec.sources[0]` is what produced a real bug in the previous CRD reader, and
 * editing only the first source of a multi-source app would silently ignore the
 * rest -- so every source gets its own field.
 */

function sourcesOf(spec) {
  if (!spec) return [];
  if (spec.source) return [{ ...spec.source, __single: true }];
  return (spec.sources || []).map((source) => ({ ...source }));
}

function sourceTitle(source, index, total) {
  if (total === 1) return 'Source';
  const label = source.chart || source.path || source.ref || `source ${index + 1}`;
  return `Source ${index + 1}: ${label}`;
}

export default function SourceEditor({
  opened,
  onClose,
  app,
  ownedByApplicationSet,
  onSave,
  saving,
  error,
  degraded = false,
}) {
  const originalSources = useMemo(() => sourcesOf(app?.spec), [app]);
  const [drafts, setDrafts] = useState([]);

  useEffect(() => {
    if (opened) setDrafts(originalSources.map((source) => ({ ...source })));
  }, [opened, originalSources]);

  const changed = useMemo(
    () =>
      drafts.some((draft, index) => {
        const original = originalSources[index];
        if (!original) return false;
        return (
          draft.targetRevision !== original.targetRevision ||
          draft.path !== original.path ||
          draft.chart !== original.chart
        );
      }),
    [drafts, originalSources]
  );

  const update = (index, patch) =>
    setDrafts((current) => current.map((draft, i) => (i === index ? { ...draft, ...patch } : draft)));

  const submit = () => {
    // Rebuild the spec in whichever form it originally used, so a single-source
    // app is not silently converted into a multi-source one.
    const spec = { ...app.spec };
    if (app.spec?.source) {
      const { __single, ...source } = drafts[0] || {};
      spec.source = source;
    } else {
      spec.sources = drafts.map(({ __single, ...source }) => source);
    }
    onSave?.(spec);
  };

  return (
    <Modal opened={opened} onClose={onClose} title="Edit application source" size="lg">
      <Stack gap="md">
        {ownedByApplicationSet && (
          <Alert
            variant="light"
            color="statusError"
            icon={<IconAlertTriangle size={18} />}
            title="This application is generated by an ApplicationSet"
          >
            Changes here will be reverted the next time the generator reconciles. Edit the
            ApplicationSet template instead.
          </Alert>
        )}

        {degraded && (
          <Alert variant="light" color="statusWarn" icon={<IconAlertTriangle size={18} />} title="Editing unavailable">
            Changing the source needs the ArgoCD API, which is currently unreachable.
          </Alert>
        )}

        {app?.spec?.syncPolicy?.automated && (
          <Alert variant="light" color="statusInfo" title="Automated sync is enabled">
            Saving will trigger a deployment of the new revision automatically.
          </Alert>
        )}

        {drafts.map((draft, index) => (
          <Paper key={index} withBorder p="md" radius="md">
            <Stack gap="sm">
              <Group gap="xs">
                <IconGitBranch size={16} />
                <Text size="sm" fw={600}>
                  {sourceTitle(draft, index, drafts.length)}
                </Text>
                {draft.chart ? (
                  <Badge size="xs" variant="light">helm chart</Badge>
                ) : (
                  <Badge size="xs" variant="light">git</Badge>
                )}
              </Group>

              <Text size="xs" c="dimmed">
                {draft.repoURL}
              </Text>

              <TextInput
                label={draft.chart ? 'Chart version' : 'Target revision'}
                description={
                  draft.chart
                    ? 'Helm chart version, e.g. 1.13.4'
                    : 'Branch, tag or commit SHA, e.g. main, v1.2.3, HEAD'
                }
                value={draft.targetRevision || ''}
                onChange={(event) => update(index, { targetRevision: event.currentTarget.value })}
                rightSection={
                  originalSources[index]?.targetRevision !== draft.targetRevision ? (
                    <Badge size="xs" color="statusWarn">changed</Badge>
                  ) : null
                }
                rightSectionWidth={72}
                disabled={degraded}
              />

              {draft.chart ? (
                <TextInput
                  label="Chart"
                  value={draft.chart || ''}
                  onChange={(event) => update(index, { chart: event.currentTarget.value })}
                  disabled={degraded}
                />
              ) : (
                <TextInput
                  label="Path"
                  description="Directory within the repository"
                  value={draft.path || ''}
                  onChange={(event) => update(index, { path: event.currentTarget.value })}
                  disabled={degraded}
                />
              )}
            </Stack>
          </Paper>
        ))}

        {changed && (
          <>
            <Divider label="Pending changes" labelPosition="center" />
            <Paper withBorder p="sm" radius="md">
              <Stack gap={4}>
                {drafts.map((draft, index) => {
                  const original = originalSources[index];
                  if (!original) return null;
                  const diffs = [];
                  if (draft.targetRevision !== original.targetRevision) {
                    diffs.push(['revision', original.targetRevision || '(none)', draft.targetRevision || '(none)']);
                  }
                  if (draft.path !== original.path) {
                    diffs.push(['path', original.path || '(none)', draft.path || '(none)']);
                  }
                  if (draft.chart !== original.chart) {
                    diffs.push(['chart', original.chart || '(none)', draft.chart || '(none)']);
                  }
                  return diffs.map(([field, from, to]) => (
                    <Group key={`${index}-${field}`} gap="xs" wrap="nowrap">
                      <Text size="xs" c="dimmed" w={70}>{field}</Text>
                      <Code>{from}</Code>
                      <Text size="xs">→</Text>
                      <Code>{to}</Code>
                    </Group>
                  ));
                })}
              </Stack>
            </Paper>
          </>
        )}

        {error && <ErrorState error={error} title="Could not update the source" />}

        <Group justify="flex-end" gap="xs">
          <Button variant="subtle" onClick={onClose}>Cancel</Button>
          <Button onClick={submit} loading={saving} disabled={!changed || degraded}>
            Save source
          </Button>
        </Group>
      </Stack>
    </Modal>
  );
}
