apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csoc.fullname" . }}
  labels:
    {{- include "csoc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csoc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "csoc.serviceAccountName" .) }}

      volumes:
        # - name: {{ .Values.volumes.config.name }}
        #   configMap:
        #     name: {{ .Values.volumes.config.configMapName }}
        - name: {{ .Values.volumes.data.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}

      containers:
        # ================= API =================
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.api.workingDir }}

          {{ with .Values.api.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          ports:
            - containerPort: {{ .Values.api.ports.http }}
            - containerPort: {{ .Values.api.ports.grpc }}

          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

          volumeMounts:
            {{- toYaml .Values.api.volumeMounts | nindent 12 }}

        # ================= FRONTEND =================
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.ports.http }}

          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}

          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
