apiVersion: v1
kind: Service
metadata:
  name: {{ include "csoc.fullname" . }}
  labels:
    {{- include "csoc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "csoc.selectorLabels" . | nindent 4 }}

  ports:
    # Frontend
    - name: frontend
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP

    # API
    - name: api
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csoc.fullname" . }}-grpc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
  labels:
    {{- include "csoc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.grpc.type }}
  selector:
    {{- include "csoc.selectorLabels" . | nindent 4 }}

  ports:
    # gRPC
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
